detection_triggers:
- topic: /detection_trigger/camera_near
  transition: [[0.9, 0.1], [0.1, 0.9]]
  schedule:
  - from: 6
    to: 19
    likelihood: [[0.6, 0.45], [0.4, 0.55]]
  threshold: 0.8
- topic: /detection_trigger/camera_near_zoomed
  transition: [[0.9, 0.1], [0.1, 0.9]]
  schedule:
  - from: 6
    to: 19
    likelihood: [[0.6, 0.45], [0.4, 0.55]]
  threshold: 0.8
- topic: /detection_trigger/camera_near_zoomed2
  transition: [[0.9, 0.1], [0.1, 0.9]]
  schedule:
  - from: 6
    to: 19
    likelihood: [[0.6, 0.45], [0.4, 0.55]]
  threshold: 0.8
- topic: /detection_trigger/camera_far
  transition: [[0.9, 0.1], [0.1, 0.9]]
  schedule:
  - from: 6
    to: 19
    likelihood: [[0.6, 0.45], [0.4, 0.55]]
  threshold: 0.8
- topic: /detection_trigger/camera_thermal
  transition: [[0.9, 0.1], [0.1, 0.9]]
  schedule:
  - from: 0
    to: 24
    likelihood: [[0.6, 0.45], [0.4, 0.55]]
  threshold: 1.0
