camera_ns: "camera_centre"
frame_id: "camera_centre_link"
camera_serial: 232902059
camera_info_url: "file:///ros_ws/src/lucid-hdr-gige-cam/config/camera_info.yaml"
pixel_format: RGB8
trigger_mode: 0
trigger_fps: 2
use_binning: false
exposure_time_us: 10000
use_ptp_time: false
use_max_packet_size: false
use_system_default_qos: true
viz: true
